# https://taskfile.dev
version: "3"

tasks:
  release:
    desc: build and publish release
    cmds:
      - test {{.CLI_ARGS}}
      - grep -F '"{{.CLI_ARGS}}"' build.zig.zon
      - git tag {{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}
  format:
    desc: "run code formatters"
    cmds:
      - zig fmt .
  test:audio:
    dir: examples/audio
    cmds: [zig build]
  test:input:
    dir: examples/input
    cmds: [zig build]
  test:triangle:
    dir: examples/triangle
    cmds: [zig build]
  test:
    desc: "run tests"
    cmds:
      - task: test:audio
      - task: test:input
      - task: test:triangle
  all:
    cmds:
      - task: format
      - task: test
  default:
    - task: all
